### ISSUE TITLE
Cache Results of the Exists CQL Expression

### ISSUE THREAD

**Issue by juliangruendner** [samply/blaze#1051]
The CQL cache is deactivated per default. In order to activate it, please set the env var `CQL_EXPR_CACHE_SIZE` to a value of the size of the cache in MiB.

## Todos

* [x] generate new PatientAsOf index on the fly without the need to generate all indices
  * [x] generation works
  * [x] investigate memory leak
  * [x] prevent repetitive index generation on once successfully generated index  
* [x] ensure that all CQL expressions have a form
* [ ] test with real data and evaluate the cache hit ratio
* [x] allow to disable the cache
* [x] document the improved performance results
  * [x] 100k on LEA47
  * [x] 1M on LEA47
  * [x] 1M on LEA58 
* [x] don't cache excessive big expressions
* [x] constrain the Bloom filter generation queue
* [ ] show stats in the UI
